### ISSUE TITLE
Documentation for development environment and pip editable install

### ISSUE THREAD

**Issue by scottyhq** [stac-utils/stactools#98] opened 2021-04-29 07:40 UTC
I'm not accustomed to working with subpackages and pip so maybe I'm missing something, but I spent a while trying to setup a development environment for #84. Wanted to document some things here, and could follow up with some additions to documentation. I think this is also related to discussion in https://github.com/stac-utils/stactools/issues/95. 

For Python package development I'm accustomed to installing in 'editable' mode (`pip install -e`) into a virtual environment. For example: 
```
conda create -n stactools-dev python 
conda activate stactools-dev
git clone https://github.com/stac-utils/stactools.git
cd stactools
pip install -e . 
# Successfully installed stactools-0.1.4
```

If I try to run command line tools (`scripts/stac --help`), I end up with a traceback. This comes from the `threedep` subpackage, which I was not intending on installing or working with:
```pytb
Traceback (most recent call last):
  File "/Users/scott/miniconda3/envs/stactools-test/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/scott/miniconda3/envs/stactools-test/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/scott/miniconda3/envs/stactools-test/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/scott/Downloads/stactools/stactools/cli/__init__.py", line 27, in <module>
    registry.load_plugins()
  File "/Users/scott/Downloads/stactools/stactools/cli/registry.py", line 29, in load_plugins
    discovered_plugins = {
  File "/Users/scott/Downloads/stactools/stactools/cli/registry.py", line 30, in <dictcomp>
    name: importlib.import_module(name)
  File "/Users/scott/miniconda3/envs/stactools-test/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/scott/Downloads/stactools/stactools/threedep/__init__.py", line 3, in <module>
    from stactools.threedep.metadata import Metadata
  File "/Users/scott/Downloads/stactools/stactools/threedep/metadata.py", line 14, in <module>
    from stactools.threedep import utils
  File "/Users/scott/Downloads/stactools/stactools/threedep/utils.py", line 3, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

But to get around it installed the threedep subpackage: `pip install stactools_threedep` and then re-run `scripts/stac --help`
```pytb
Traceback (most recent call last):
  File "/Users/scott/miniconda3/envs/stactools-test/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/scott/miniconda3/envs/stactools-test/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/scott/miniconda3/envs/stactools-test/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/scott/Downloads/stactools/stactools/cli/__init__.py", line 27, in <module>
    registry.load_plugins()
  File "/Users/scott/Downloads/stactools/stactools/cli/registry.py", line 37, in load_plugins
    register_plugin(self)
  File "/Users/scott/Downloads/stactools/stactools/aster/__init__.py", line 11, in register_plugin
    from stactools.aster import commands
  File "/Users/scott/Downloads/stactools/stactools/aster/commands.py", line 9, in <module>
    from stactools.aster.cog import create_cogs
  File "/Users/scott/Downloads/stactools/stactools/aster/cog.py", line 14, in <module>
    from stactools.aster.xml_metadata import XmlMetadata
  File "/Users/scott/Downloads/stactools/stactools/aster/xml_metadata.py", line 9, in <module>
    from stactools.core.io.xml import XmlElement
  File "/Users/scott/Downloads/stactools/stactools/core/io/xml.py", line 4, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

Strange b/c lxml is a dependency of stactools_core. glancing at the logs, I'm surprised that subpackages are not installed from local source, and instead are downloaded, not sure if that is related to lxml not ending up in the environment? 
```
Obtaining file:///Users/scott/Downloads/stactools
Collecting stactools_core==0.1.4
  Downloading stactools_core-0.1.4-py3-none-any.whl (7.3 kB)
```

### workaround

What I'm currently doing is looping through all the subdirectories, maybe there is a better way?
```
conda create -n stactools-dev python 
conda activate stactools-dev
git clone https://github.com/stac-utils/stactools.git
cd stactools
pip install -e .
for dir in stactools_*; do (cd "$dir" && pip install -e .); done
```
After that I'm able to modify code (create a sentinel1 package and run terminal commands like `stac sentinel1 create-item --help`)

**Comment by gadomski** [comment] 2021-04-29 18:16
I am able to reproduce (or at least get a similar-ish result) to all of the errors. In my opinion, everything you're trying to do is sane, so my preference would be correct the package setup to allow your use case to work (rather than writing documentation telling you to change your ways :-P). Seems like there's two main problems here:

1. An editable install includes the [top level symlink directory](https://github.com/stac-utils/stactools/tree/299968ac10b6614bba3f72226eecb317831a368a/stactools), which puts _all packages_ into the `stactools` package namespace, even if you didn't install them. This is then picked up by the [plugin registry](https://github.com/stac-utils/stactools/blob/299968ac10b6614bba3f72226eecb317831a368a/stactools_cli/stactools/cli/registry.py#L12-L37).
2. All installs look for pip-hosted versions of dependency packages, including `stactools_core`. This can lead to breakages (e.g. if you try to `pip install 'git+https://github.com/stac-utils/stactools#egg=stactools[all]'` right now it'll break, because `stactools-threedep` is not registered on PyPi).

The first issue can be fixed by removing that top level symlink directory. This would allow editable installs to work w/o installing all subpackages. The downside would be that development setups would not be able to drop into python in the top-level directory and just do a `import stactools.naip` or whatever. IMO this tradoff is ok, but interested what others think.

The second one is trickier. You could try to work around it by specifying the subpackage dependency location in the `extras_require` as a url to the **stactools** github location, but that feels too clever by half. I wonder if the `extra_requires` effort is worth it, or if we drop support for that and make everyone enumerate the subpackages they want explicitly (or maybe provide a convenience script to install them all). I'm going to think about this one more.

**Closed** 2021-06-10 19:10 UTC
Labels: bug, documentation
