### ISSUE TITLE
What should go in a subpackage's requirements.txt?

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#95] opened 2021-04-28 20:24 UTC
As raised in https://github.com/stac-utils/stactools/pull/84#discussion_r622361095 and the subsequent discussion, it's not clear how **stactools** subpackages should define their dependencies. Should subpackages explicitly call out every third-party package they use (e.g. **rasterio**), even if these packages are also required in **stacutils_core**?

I've pulled out the main arguments below. Once we resolve the question, we should
1. Update all subpackages to conform, and
2. Document the decision in https://github.com/stac-utils/stactools#adding-a-new-sub-package

## All third-party package dependencies

As @kylebarron said (https://github.com/stac-utils/stactools/pull/84#discussion_r622429380):

> It makes it more complicated if you have to remember "well we import rasterio, but use it as a side effect of stactools-core, so if we ever change that dependency in stactools-core, we'll have to remember it has changes here"

## Only dependencies not included in **stactools_core**

I thought (https://github.com/stac-utils/stactools/pull/84#discussion_r622443637):

> These packages are tightly coupled such that **stactools_sentinel1** is never going to live in an environment w/o **stactools_core**.

also

> By repeating the dependency multiple places in the same environment, you might inadvertently overwrite a pinned dependency, e.g. the bare **rasterio dependency** in this PR (#84) could do a major/minor **rasterio** bump over the pinned version in **stactools_core**.

**Comment by kylebarron** [comment] 2021-04-29 00:45
> It's been this repo's convention to pin dependencies to a tiny version. By repeating the dependency multiple places in the same environment, you might inadvertently overwrite a pinned dependency, e.g. the bare rasterio dependency in this PR could do a major/minor rasterio bump over the pinned version in stactools_core.

I think the dependency should be explicitly listed in each package, _but that doesn't mean the version needs to be managed there_. For example, in the current `stac-fastapi` namespace packaging setup, the version of each submodule is [retrieved from some global location](https://github.com/stac-utils/stac-fastapi/blob/af0750ff5daa7a3977c371987ce8deddb240e107/stac_fastapi/api/setup.py#L10-L14).

The corollary here is that you can have a top-level text file that describes versions of dependencies you need to pin. E.g. `dependency_versions.json`:
```json
{
  "rasterio": "1.1.8"
}
```

Then in each namespace package's `setup.py`, you can have
```py
with open('../../dependency_versions.json') as f:
    pinned_versions = json.load(f)

install_requires = {
    f'rasterio=={pinned_versions.get('rasterio', '')}'
}
```
(obviously here you want something slightly more intelligent, so that you don't have `name==`.)

I see you already do this with internal dependencies; no reason not to do this with external ones too:
https://github.com/stac-utils/stactools/blob/33784e18129e4a153d1ab97bffe7615b37c733aa/stactools_landsat/setup.py#L25

> I've been in the practice of pinning to specific versions after getting burned by debugging things that are caused by a version upgrade that I didn't expect in a dependency. However, pinning to a specific version in something that is pulled in as a dependency can be a pain if the downstream user's project depends on another version that would work just fine but makes pip unhappy due to version mismatch. I'm not sure the best solution for this - perhaps relaxing the version restrictions to major versions and hoping dependencies keep close to semver?

I think this is a more general Python dependency management complaint, and I think the main question here is: are stactools modules intended to be used as _libraries_ in downstream applications, or _as applications themselves_ (for example through use of a CLI directly). Each has different requirements; for libraries it's much nicer to have a range of allowed versions so that downstream users don't need one exact dependency version. For applications you ideally have lockfiles that are checked in to Git so that you can re-run a CLI with the _exact_ same set of dependencies. Note that pinning dependencies inside `requirements.txt` does not match this description, because if you pin `rasterio==1.1.8`, but rasterio doesn't pin all of _its_ dependencies, and one of _its_ dependencies is upgraded, you might receive that upgraded sub dependency on next install.

I've been reasonably happy with [Poetry](https://python-poetry.org/) here. `setup.py` files can adequately handle the first case (libraries) by specifying a range of dependencies, but in my opinion Poetry (or pipenv, etc) make it much easier to have fully reproducible lockfiles.

I should also note that in some occasions a Python package is both a library and an application, in which case it makes sense that you have both a package definition with a range of dependencies _and_ a reproducible lockfile.

**Closed** 2021-06-10 19:10 UTC
Labels: question
